name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Build React App
        run: |
          npm install
          npm run build

      - name: Deploy to Firebase (main branch)
        if: github.ref == 'refs/heads/main'
        run: firebase deploy --only hosting --token "$FIREBASE_TOKEN"

      - name: Deploy to Firebase (dev branch)
        if: github.ref == 'refs/heads/dev'
        run: firebase hosting:channel:deploy dev --token "$FIREBASE_TOKEN"
