name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy-main:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Firebase CLI and dotenv-cli
        run: npm install -g firebase-tools dotenv-cli

      - name: Install Dependencies
        run: npm install

      - name: Decode Firebase Service Account Key
        run: echo "${{ secrets.FIREBASE_SERVICE_KEY }}" | base64 --decode > firebase-key.json

      - name: Create .env file
        run: |
          echo "REACT_APP_FIREBASE_API_KEY=${{ secrets.REACT_APP_FIREBASE_API_KEY }}" >> .env
          echo "REACT_APP_RAPIDAPI_KEY=${{ secrets.REACT_APP_RAPIDAPI_KEY }}" >> .env
          echo "REACT_APP_RAPIDAPI_HOST=${{ secrets.REACT_APP_RAPIDAPI_HOST }}" >> .env
          echo "REACT_APP_BACKEND_HOST=${{ secrets.REACT_APP_BACKEND_HOST }}" >> .env
          echo "REACT_APP_FRONTEND_HOST=${{ secrets.REACT_APP_FRONTEND_HOST }}" >> .env
          echo "BACKEND_PORT=${{ secrets.BACKEND_PORT }}" >> .env

      - name: Build Project (Main)
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/firebase-key.json
        run: dotenv npm run build

      - name: Deploy to Firebase (Main)
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/firebase-key.json
        run: firebase deploy --only hosting:main

  deploy-dev:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Firebase CLI and dotenv-cli
        run: npm install -g firebase-tools dotenv-cli

      - name: Install Dependencies
        run: npm install

      - name: Decode Firebase Service Account Key
        run: echo "${{ secrets.FIREBASE_SERVICE_KEY }}" | base64 --decode > firebase-key.json

      - name: Create .env file
        run: |
          echo "REACT_APP_FIREBASE_API_KEY=${{ secrets.REACT_APP_FIREBASE_API_KEY }}" >> .env
          echo "REACT_APP_RAPIDAPI_KEY=${{ secrets.REACT_APP_RAPIDAPI_KEY }}" >> .env
          echo "REACT_APP_RAPIDAPI_HOST=${{ secrets.REACT_APP_RAPIDAPI_HOST }}" >> .env
          echo "REACT_APP_BACKEND_HOST=${{ secrets.REACT_APP_BACKEND_HOST }}" >> .env
          echo "REACT_APP_FRONTEND_HOST=${{ secrets.REACT_APP_FRONTEND_HOST }}" >> .env
          echo "BACKEND_PORT=${{ secrets.BACKEND_PORT }}" >> .env

      - name: Build Project (Dev)
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/firebase-key.json
        run: dotenv npm run build

      - name: Deploy to Firebase (Dev)
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/firebase-key.json
        run: firebase deploy --only hosting:dev
