name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy-main:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Install Dependencies
        run: npm install

      # Decode the base64 secret into a file
      - name: Setup Firebase Service Account
        run: echo "${{ secrets.FIREBASE_SERVICE_KEY }}" | base64 --decode > "$GITHUB_WORKSPACE/firebase-key.json"

      - name: Debug Check for Service Account File
        run: |
          echo "Listing $GITHUB_WORKSPACE:"
          ls -la $GITHUB_WORKSPACE
          echo "File size of firebase-key.json:"
          stat -c%s "$GITHUB_WORKSPACE/firebase-key.json" || stat -f%z "$GITHUB_WORKSPACE/firebase-key.json"

      - name: Create .env file
        run: |
          echo "REACT_APP_FIREBASE_API_KEY=${{ secrets.REACT_APP_FIREBASE_API_KEY }}" >> .env
          echo "REACT_APP_RAPIDAPI_KEY=${{ secrets.REACT_APP_RAPIDAPI_KEY }}" >> .env
          echo "REACT_APP_RAPIDAPI_HOST=${{ secrets.REACT_APP_RAPIDAPI_HOST }}" >> .env
          echo "REACT_APP_BACKEND_HOST=${{ secrets.REACT_APP_BACKEND_HOST }}" >> .env
          echo "REACT_APP_FRONTEND_HOST=${{ secrets.REACT_APP_FRONTEND_HOST }}" >> .env
          echo "BACKEND_PORT=${{ secrets.BACKEND_PORT }}" >> .env

      - name: Build Main Branch
        env:
          CI: false
          REACT_APP_FIREBASE_API_KEY: ${{ secrets.REACT_APP_FIREBASE_API_KEY }}
          REACT_APP_RAPIDAPI_KEY: ${{ secrets.REACT_APP_RAPIDAPI_KEY }}
          REACT_APP_RAPIDAPI_HOST: ${{ secrets.REACT_APP_RAPIDAPI_HOST }}
          REACT_APP_BACKEND_HOST: ${{ secrets.REACT_APP_BACKEND_HOST }}
          REACT_APP_FRONTEND_HOST: ${{ secrets.REACT_APP_FRONTEND_HOST }}
          BACKEND_PORT: ${{ secrets.BACKEND_PORT }}
          FIREBASE_SERVICE_KEY: ${{ secrets.FIREBASE_SERVICE_KEY }}
          GOOGLE_APPLICATION_CREDENTIALS: "$GITHUB_WORKSPACE/firebase-key.json"
        run: npm run build

      - name: Deploy to Firebase Main
        env:
          GOOGLE_APPLICATION_CREDENTIALS: "$GITHUB_WORKSPACE/firebase-key.json"
        run: |
          export GOOGLE_APPLICATION_CREDENTIALS="$GITHUB_WORKSPACE/firebase-key.json"
          firebase deploy --only hosting:main

  deploy-dev:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Install Dependencies
        run: npm install

      - name: Setup Firebase Service Account
        run: echo "${{ secrets.FIREBASE_SERVICE_KEY }}" | base64 --decode > "$GITHUB_WORKSPACE/firebase-key.json"

      - name: Debug Check for Service Account File
        run: |
          echo "Listing $GITHUB_WORKSPACE:"
          ls -la $GITHUB_WORKSPACE
          echo "File size of firebase-key.json:"
          stat -c%s "$GITHUB_WORKSPACE/firebase-key.json" || stat -f%z "$GITHUB_WORKSPACE/firebase-key.json"

      - name: Create .env file
        run: |
          echo "REACT_APP_FIREBASE_API_KEY=${{ secrets.REACT_APP_FIREBASE_API_KEY }}" >> .env
          echo "REACT_APP_RAPIDAPI_KEY=${{ secrets.REACT_APP_RAPIDAPI_KEY }}" >> .env
          echo "REACT_APP_RAPIDAPI_HOST=${{ secrets.REACT_APP_RAPIDAPI_HOST }}" >> .env
          echo "REACT_APP_BACKEND_HOST=${{ secrets.REACT_APP_BACKEND_HOST }}" >> .env
          echo "REACT_APP_FRONTEND_HOST=${{ secrets.REACT_APP_FRONTEND_HOST }}" >> .env
          echo "BACKEND_PORT=${{ secrets.BACKEND_PORT }}" >> .env

      - name: Build Dev Branch
        env:
          CI: false
          REACT_APP_FIREBASE_API_KEY: ${{ secrets.REACT_APP_FIREBASE_API_KEY }}
          REACT_APP_RAPIDAPI_KEY: ${{ secrets.REACT_APP_RAPIDAPI_KEY }}
          REACT_APP_RAPIDAPI_HOST: ${{ secrets.REACT_APP_RAPIDAPI_HOST }}
          REACT_APP_BACKEND_HOST: ${{ secrets.REACT_APP_BACKEND_HOST }}
          REACT_APP_FRONTEND_HOST: ${{ secrets.REACT_APP_FRONTEND_HOST }}
          BACKEND_PORT: ${{ secrets.BACKEND_PORT }}
          FIREBASE_SERVICE_KEY: ${{ secrets.FIREBASE_SERVICE_KEY }}
          GOOGLE_APPLICATION_CREDENTIALS: "$GITHUB_WORKSPACE/firebase-key.json"
        run: npm run build

      - name: Deploy to Firebase Dev
        env:
          GOOGLE_APPLICATION_CREDENTIALS: "$GITHUB_WORKSPACE/firebase-key.json"
        run: |
          export GOOGLE_APPLICATION_CREDENTIALS="$GITHUB_WORKSPACE/firebase-key.json"
          firebase deploy --only hosting:dev
