name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy-main:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Install Dependencies
        run: npm install

      - name: Setup Google Authentication
        run: echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" | base64 --decode > "$HOME/firebase-key.json"

      - name: Build Main Branch
        env:
          CI: false
          REACT_APP_FIREBASE_API_KEY: ${{ secrets.REACT_APP_FIREBASE_API_KEY }}
          REACT_APP_RAPIDAPI_KEY: ${{ secrets.REACT_APP_RAPIDAPI_KEY }}
          REACT_APP_RAPIDAPI_HOST: ${{ secrets.REACT_APP_RAPIDAPI_HOST }}
          REACT_APP_BACKEND_HOST: ${{ secrets.REACT_APP_BACKEND_HOST }}
          BACKEND_PORT: ${{ secrets.BACKEND_PORT }}
        run: npm run build

      - name: Deploy to Firebase Main
        env:
          GOOGLE_APPLICATION_CREDENTIALS: "$HOME/firebase-key.json"
        run: |
          export GOOGLE_APPLICATION_CREDENTIALS="$HOME/firebase-key.json"
          firebase deploy --only hosting:main

  deploy-dev:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Install Dependencies
        run: npm install

      - name: Setup Google Authentication
        run: echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" | base64 --decode > "$HOME/firebase-key.json"

      - name: Build Dev Branch
        env:
          CI: false
          REACT_APP_FIREBASE_API_KEY: ${{ secrets.REACT_APP_FIREBASE_API_KEY }}
          REACT_APP_RAPIDAPI_KEY: ${{ secrets.REACT_APP_RAPIDAPI_KEY }}
          REACT_APP_RAPIDAPI_HOST: ${{ secrets.REACT_APP_RAPIDAPI_HOST }}
          REACT_APP_BACKEND_HOST: ${{ secrets.REACT_APP_BACKEND_HOST }}
          BACKEND_PORT: ${{ secrets.BACKEND_PORT }}
        run: npm run build

      - name: Deploy to Firebase Dev
        env:
          GOOGLE_APPLICATION_CREDENTIALS: "$HOME/firebase-key.json"
        run: |
          export GOOGLE_APPLICATION_CREDENTIALS="$HOME/firebase-key.json"
          firebase deploy --only hosting:dev
